name: atcs
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pip=24.0=pyhd8ed1ab_0
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.4
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - async-timeout==4.0.3
      - black==24.4.0
      - blis==0.7.11
      - catalogue==2.0.10
      - click==8.1.7
      - cloudpathlib==0.16.0
      - confection==0.1.4
      - contourpy==1.2.1
      - cycler==0.12.1
      - cymem==2.0.8
      - datasets==2.18.0
      - dill==0.3.8
      - filelock==3.13.4
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - grpcio==1.62.1
      - huggingface-hub==0.22.2
      - iniconfig==2.0.0
      - isort==5.13.2
      - kiwisolver==1.4.5
      - langcodes==3.3.0
      - lightning==2.2.1
      - lightning-utilities==0.11.2
      - markdown==3.6
      - matplotlib==3.8.4
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - mypy-extensions==1.0.0
      - networkx==3.3
      - numpy==1.26.4
      - pandas==2.2.2
      - pathspec==0.12.1
      - pillow==10.3.0
      - pluggy==1.4.0
      - preshed==3.0.9
      - protobuf==5.26.1
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pyparsing==3.1.2
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.2.1
      - regex==2023.12.25
      - safetensors==0.4.3
      - smart-open==6.4.0
      - spacy==3.7.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - sympy==1.12
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - thinc==8.2.3
      - tokenize-rt==5.2.0
      - tokenizers==0.15.2
      - torch==2.2.2
      - torchmetrics==1.3.2
      - torchtext==0.17.2
      - torchvision==0.17.2
      - tqdm==4.66.2
      - transformers==4.39.3
      - typer==0.9.4
      - tzdata==2024.1
      - wasabi==1.1.2
      - weasel==0.3.4
      - werkzeug==3.0.2
      - xxhash==3.4.1
      - yarl==1.9.4
      - jupyter==1.0.0
      - scikit-learn==1.4.2
