#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=senteval
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=03:00:00
#SBATCH --output=output/senteval_%A.out

module purge
module load 2022
module load Anaconda3/2022.05
# cd to dir
cd $HOME/learning-sentence-representations/

conda env remove --name atcs
# create env
conda env create -f environment.yaml
# activate env
source activate atcs

python run_senteval.py
