#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=train_models
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --time=10:00:00
#SBATCH --mem=16000M
#SBATCH --output=output/train_model_%A.out

module purge
module load 2022
module load Anaconda3/2022.05
# cd to dir
cd $HOME/learning-sentence-representations/
# create env
conda env create -f environment.yaml
# activate env
source activate atcs

bash ./train_all_models.sh
