#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=4
#SBATCH --job-name=verify_train_models_distributed
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=01:00:00
#SBATCH --mem=16000M
#SBATCH --output=output/verify_train_models_distributed_%A.out

module purge
module load 2022
module load Anaconda3/2022.05
# cd to dir
cd $HOME/learning-sentence-representations/
# create env
conda env create -f environment.yaml
# activate env
source activate atcs

bash ./verify_train_all_models.sh
